#!/usr/bin/env node

var jscss = require("./index");
var fs = require("fs");
var argv = require("optimist").argv;
var input;

if (argv._[0]) {
  input = fs.readFileSync("./" + argv._[0]).toString();
}
else {
  console.log("Usage: jscss [file]");
  process.exit();
}

if (!process.argv[2]) {
  console.log("Usage: index.js [file]");
  process.exit();
}

console.log(jscss(input));
